In [1]:
#1) Combining a one and a two-dimensional NumPy Array

import numpy as np

a = np.array([1, 2, 3])

b = np.array([
    [4, 5, 6],
    [7, 8, 9]
])

result = np.vstack((a, b))

print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
#2) Flatten a 2d numpy array into 1d array

import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

result = arr.flatten()

print(result)

[1 2 3 4 5 6]


In [3]:
#3) Reverse a numpy array 

import numpy as np

arr = np.array([10, 20, 30, 40, 50])

reverse_arr = arr[::-1]

print(reverse_arr)



[50 40 30 20 10]


In [4]:
#4) Practice operations like Get the maximum value from given array Get the minimum value from given array Find the number of rows and columns of a given array using NumPy Select the elements from a given array (each element and specific element) Find the sum of values in a 2D array using for loop Adding, Subtracting, multiplying, dividing arrays in Numpy

import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(np.max(arr))

50


In [5]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(np.min(arr))

10


In [6]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Rows =", arr.shape[0])
print("Columns =", arr.shape[1])

Rows = 2
Columns = 3


In [7]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(arr)

print(arr[0][1])

[[10 20 30]
 [40 50 60]]
20


In [8]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

total = 0

for row in arr:
    for value in row:
        total = total + value

print(total)

21


In [9]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(a + b)

[11 22 33]


In [10]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(a - b)

[ 9 18 27]


In [11]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(a * b)

[10 40 90]


In [12]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(a / b)

[10. 10. 10.]


In [13]:
# 5) Iterate 3D array using for loop and nditer 

import numpy as np

arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

for i in arr:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8


In [14]:
import numpy as np

arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6
7
8


In [ ]:
#6) Study the following program import numpy as np # create a numpy 1d-arrays arr1 = np.array([3, 4]) arr2 = np.array([1, 0]) # find average of NumPy arrays avg = (arr1 + arr2) / 2 print("Average of NumPy arrays:\n", avg) -> Calculate average mean median mode values of two NumPy 2d-arrays

import numpy as np
from scipy import stats

arr1 = np.array([
    [10, 20],
    [30, 40]
])

arr2 = np.array([
    [50, 60],
    [70, 80]
])

avg = (arr1 + arr2) / 2

print("Average:")
print(avg)

combined = np.concatenate((arr1, arr2))

print("Mean =", np.mean(combined))
print("Median =", np.median(combined))

mode = stats.mode(combined, axis=None)

print("Mode =", mode.mode)