In [ ]:
#1) Replace Nan with 0 and Interchange 3 rows and 3 columns of 2D array [[6, -8, 73, -110], [np.nan, -8, 0, 94]]

import numpy as np

arr = np.array([[6, -8, 73, -110], [np.nan, -8, 0, 94]])
arr = np.nan_to_num(arr, nan=0.0)
result = arr.T
print(result)

[[   6.    0.]
 [  -8.   -8.]
 [  73.    0.]
 [-110.   94.]]


In [2]:
#2) Move axes of 3D array to new positions

import numpy as np

arr = np.zeros((2, 3, 4))
result = np.moveaxis(arr, source=[0, 1, 2], destination=[2, 0, 1])
print(result.shape)


(3, 4, 2)


In [3]:
#3) Replace NaN values with average of columns 4) Replace negative value with zero in numpy array using replace

import numpy as np

arr = np.array([[1.0, -2.0, np.nan], [3.0, 4.0, 5.0], [np.nan, -6.0, 7.0]])

col_mean = np.nanmean(arr, axis=0)
inds = np.where(np.isnan(arr))
arr[inds] = np.take(col_mean, inds[1])

arr = np.where(arr < 0, 0, arr)

print(arr)


[[1. 0. 6.]
 [3. 4. 5.]
 [2. 0. 7.]]
