In [1]:
#1) Create numpy array and perform following operation > Convert 1D array to 2D > Print Array Attributes(Like shape, dimenssion, data type, itemsize) > Create a 3×3 NumPy array of all 9 > Create a 1D array of 10 evenly spaced values between 25 and 125 > Convert a Python list into a NumPy array > Reverse a 1D NumPy array > Create a 4×4×3 array and extract value at its second set, first row and last column > Create a 4×4 and Extract Odd Rows and Even Columns > Slice the first two rows and first two columns of econd set from a 4×4×3 array > Replace all odd numbers in a NumPy array with -1 by itterating using for loop [[23, 56, 78, 93], [71, 82,13, 24]] > Get the indices of non-zero elements in an array [1, 0, 2, 0, 3, 0, 4] > Perform arithmetic operations on two NumPy arrays element-wise Add two NumPy arrays element by element. Multiply two NumPy arrays element by element. > Write a code to compute the dot product of two NumPy arrays arr1 = [15, 20, 25] arr2 = [10,40,37]

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

print(arr.reshape(2, 3))

[[1 2 3]
 [4 5 6]]


In [2]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])

print("Shape =", arr.shape)
print("Dimension =", arr.ndim)
print("Data Type =", arr.dtype)
print("Item Size =", arr.itemsize)

Shape = (2, 2)
Dimension = 2
Data Type = int64
Item Size = 8


In [3]:
import numpy as np

arr = np.full((3, 3), 9)

print(arr)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [4]:
import numpy as np

arr = np.linspace(25, 125, 10)

print(arr)

[ 25.          36.11111111  47.22222222  58.33333333  69.44444444
  80.55555556  91.66666667 102.77777778 113.88888889 125.        ]


In [5]:
import numpy as np

lst = [10, 20, 30, 40]

arr = np.array(lst)

print(arr)

[10 20 30 40]


In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr[::-1])

[5 4 3 2 1]


In [7]:
import numpy as np

arr = np.arange(48).reshape(4, 4, 3)

print(arr[1, 0, 2])

14


In [8]:
import numpy as np

arr = np.arange(1, 17).reshape(4, 4)

print(arr[0::2, 1::2])

[[ 2  4]
 [10 12]]


In [9]:
import numpy as np

arr = np.arange(48).reshape(4, 4, 3)

print(arr[1, 0:2, 0:2])

[[12 13]
 [15 16]]


In [10]:
import numpy as np

arr = np.array([[23, 56, 78, 93],
                [71, 82, 13, 24]])

for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        if arr[i][j] % 2 != 0:
            arr[i][j] = -1

print(arr)

[[-1 56 78 -1]
 [-1 82 -1 24]]


In [11]:
import numpy as np

arr = np.array([1, 0, 2, 0, 3, 0, 4])

print(np.nonzero(arr))

(array([0, 2, 4, 6]),)


In [12]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(a + b)

[11 22 33]


In [13]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(a * b)

[10 40 90]


In [14]:
import numpy as np

arr1 = np.array([15, 20, 25])
arr2 = np.array([10, 40, 37])

print(np.dot(arr1, arr2))

1875
